import type { CountryData } from "./countryCodes";

/**
 * List of countries that it is acceptable to delete. Avoid
 * pixel-hunting micro-nations and island nations. Full list is in
 * `countryCodes`.
 */
export const validCodes : CountryData[] = [
    {"code": "AE", "name": "United Arab Emirates"},
    {"code": "AF", "name": "Afghanistan"},
    {"code": "AL", "name": "Albania"},
    {"code": "AM", "name": "Armenia"},
    {"code": "AO", "name": "Angola"},
    {"code": "AR", "name": "Argentina"},
    {"code": "AT", "name": "Austria"},
    {"code": "AU", "name": "Australia"},
    {"code": "AZ", "name": "Azerbaijan"},
    {"code": "BA", "name": "Bosnia and Herzegovina"},
    {"code": "BB", "name": "Barbados"},
    {"code": "BD", "name": "Bangladesh"},
    {"code": "BE", "name": "Belgium"},
    {"code": "BF", "name": "Burkina Faso"},
    {"code": "BG", "name": "Bulgaria"},
    {"code": "BI", "name": "Burundi"},
    {"code": "BJ", "name": "Benin"},
    {"code": "BO", "name": "Bolivia"},
    {"code": "BR", "name": "Brazil"},
    {"code": "BS", "name": "Bahamas"},
    {"code": "BT", "name": "Bhutan"},
    {"code": "BW", "name": "Botswana"},
    {"code": "BY", "name": "Belarus"},
    {"code": "BZ", "name": "Belize"},
    {"code": "CA", "name": "Canada"},
    {"code": "CD", "name": "Democratic Republic of Congo"},
    {"code": "CF", "name": "Central African Republic"},
    {"code": "CG", "name": "Republic of Congo"},
    {"code": "CH", "name": "Switzerland"},
    {"code": "CI", "name": "Côte d'Ivoire"},
    {"code": "CL", "name": "Chile"},
    {"code": "CM", "name": "Cameroon"},
    {"code": "CN", "name": "China"},
    {"code": "CO", "name": "Colombia"},
    {"code": "CR", "name": "Costa Rica"},
    {"code": "CU", "name": "Cuba"},
    {"code": "CZ", "name": "Czechia"},
    {"code": "DE", "name": "Germany"},
    {"code": "DJ", "name": "Djibouti"},
    {"code": "DK", "name": "Denmark"},
    {"code": "DO", "name": "Dominican Republic"},
    {"code": "DZ", "name": "Algeria"},
    {"code": "EC", "name": "Ecuador"},
    {"code": "EE", "name": "Estonia"},
    {"code": "EG", "name": "Egypt"},
    {"code": "EH", "name": "Western Sahara"},
    {"code": "ER", "name": "Eritrea"},
    {"code": "ES", "name": "Spain"},
    {"code": "ET", "name": "Ethiopia"},
    {"code": "FI", "name": "Finland"},
    {"code": "FR", "name": "France"},
    {"code": "GA", "name": "Gabon"},
    {"code": "GB", "name": "United Kingdom"},
    {"code": "GE", "name": "Georgia"},
    {"code": "GF", "name": "French Guiana"},
    {"code": "GH", "name": "Ghana"},
    {"code": "GL", "name": "Greenland"},
    {"code": "GM", "name": "Gambia"},
    {"code": "GN", "name": "Guinea"},
    {"code": "GQ", "name": "Equatorial Guinea"},
    {"code": "GR", "name": "Greece"},
    {"code": "GT", "name": "Guatemala"},
    {"code": "GW", "name": "Guinea-Bissau"},
    {"code": "GY", "name": "Guyana"},
    {"code": "HN", "name": "Honduras"},
    {"code": "HR", "name": "Croatia"},
    {"code": "HT", "name": "Haiti"},
    {"code": "HU", "name": "Hungary"},
    {"code": "ID", "name": "Indonesia"},
    {"code": "IE", "name": "Ireland"},
    {"code": "IN", "name": "India"},
    {"code": "IQ", "name": "Iraq"},
    {"code": "IR", "name": "Iran"},
    {"code": "IS", "name": "Iceland"},
    {"code": "IT", "name": "Italy"},
    {"code": "JO", "name": "Jordan"},
    {"code": "JP", "name": "Japan"},
    {"code": "KE", "name": "Kenya"},
    {"code": "KG", "name": "Kyrgyzstan"},
    {"code": "KH", "name": "Cambodia"},
    {"code": "KP", "name": "North Korea"},
    {"code": "KR", "name": "South Korea"},
    {"code": "XK", "name": "Kosovo"},
    {"code": "KZ", "name": "Kazakhstan"},
    {"code": "LA", "name": "Lao People's Democratic Republic"},
    {"code": "LB", "name": "Lebanon"},
    {"code": "LK", "name": "Sri Lanka"},
    {"code": "LR", "name": "Liberia"},
    {"code": "LS", "name": "Lesotho"},
    {"code": "LT", "name": "Lithuania"},
    {"code": "LV", "name": "Latvia"},
    {"code": "LY", "name": "Libya"},
    {"code": "MA", "name": "Morocco"},
    {"code": "MD", "name": "Moldova"},
    {"code": "ME", "name": "Montenegro"},
    {"code": "MG", "name": "Madagascar"},
    {"code": "MK", "name": "North Macedonia"},
    {"code": "ML", "name": "Mali"},
    {"code": "MM", "name": "Myanmar"},
    {"code": "MN", "name": "Mongolia"},
    {"code": "MR", "name": "Mauritania"},
    {"code": "MW", "name": "Malawi"},
    {"code": "MX", "name": "Mexico"},
    {"code": "MY", "name": "Malaysia"},
    {"code": "MZ", "name": "Mozambique"},
    {"code": "NA", "name": "Namibia"},
    {"code": "NE", "name": "Niger"},
    {"code": "NG", "name": "Nigeria"},
    {"code": "NI", "name": "Nicaragua"},
    {"code": "NL", "name": "Netherlands"},
    {"code": "NO", "name": "Norway"},
    {"code": "NP", "name": "Nepal"},
    {"code": "NZ", "name": "New Zealand"},
    {"code": "OM", "name": "Oman"},
    {"code": "PA", "name": "Panama"},
    {"code": "PE", "name": "Peru"},
    {"code": "PG", "name": "Papua New Guinea"},
    {"code": "PH", "name": "Philippines"},
    {"code": "PK", "name": "Pakistan"},
    {"code": "PL", "name": "Poland"},
    {"code": "PT", "name": "Portugal"},
    {"code": "PY", "name": "Paraguay"},
    {"code": "QA", "name": "Qatar"},
    {"code": "RO", "name": "Romania"},
    {"code": "RS", "name": "Serbia"},
    {"code": "RU", "name": "Russia"},
    {"code": "RW", "name": "Rwanda"},
    {"code": "SA", "name": "Saudi Arabia"},
    {"code": "SD", "name": "Sudan"},
    {"code": "SE", "name": "Sweden"},
    {"code": "SI", "name": "Slovenia"},
    {"code": "SK", "name": "Slovakia"},
    {"code": "SL", "name": "Sierra Leone"},
    {"code": "SN", "name": "Senegal"},
    {"code": "SO", "name": "Somalia"},
    {"code": "SR", "name": "Suriname"},
    {"code": "SS", "name": "South Sudan"},
    {"code": "SV", "name": "El Salvador"},
    {"code": "SY", "name": "Syria"},
    {"code": "TD", "name": "Chad"},
    {"code": "TG", "name": "Togo"},
    {"code": "TH", "name": "Thailand"},
    {"code": "TJ", "name": "Tajikistan"},
    {"code": "TL", "name": "Timor-Leste"},
    {"code": "TM", "name": "Turkmenistan"},
    {"code": "TN", "name": "Tunisia"},
    {"code": "TR", "name": "Turkey"},
    {"code": "TZ", "name": "Tanzania"},
    {"code": "UA", "name": "Ukraine"},
    {"code": "UG", "name": "Uganda"},
    {"code": "US", "name": "United States"},
    {"code": "UY", "name": "Uruguay"},
    {"code": "UZ", "name": "Uzbekistan"},
    {"code": "VE", "name": "Venezuela"},
    {"code": "VN", "name": "Vietnam"},
    {"code": "YE", "name": "Yemen"},
    {"code": "ZA", "name": "South Africa"},
    {"code": "ZM", "name": "Zambia"},
    {"code": "ZW", "name": "Zimbabwe"}
];